version: '3'

networks:
  laravel:

services:
  #Nginx Server
  nginx:
    image: library/nginx
    container_name: nginx-bassil-ali
    volumes:
    - ./src:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8088:80"
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  #Mysql Service
  mysql:
    image: library/mysql
    container_name: mysql-bassil-ali
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: bassil
      MYSQL_ROOT_PASSWORD: bassil
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  #Phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-bassil-ali
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    networks:
      - laravel

  #PHP 7.4
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-bassil-ali
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

